version: '3.4'
services:
  app:
    build:
      context: .
    command: 'npm run serve'
    volumes:
      - .:/app:cached
      - node-modules:/app/node_modules:delegated
      - aws:/root/.aws
    ports:
      - '8080:8080'
volumes:
  node-modules:
  aws:
